# Generated by Django 3.0.3 on 2020-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(verbose_name='カテゴリー')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
