# Generated by Django 3.0.3 on 2020-07-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
